const API='http://localhost:8000';
const routes=[['/','Overview'],['/attack-map','Live Attack Map'],['/events','Events Explorer'],['/waf','WAF Rulesets'],['/rate','Rate Limiting'],['/geo','Geo Policy'],['/bot','Bot Management'],['/deployments','Deployments'],['/analytics','Analytics'],['/runbooks','Runbooks']];
let state={events:[],waf:[],snapshot:null};

async function j(url,opts){const r=await fetch(url,opts);if(!r.ok)return null;return r.json();}
async function refresh(){state.events=(await j(`${API}/api/events?limit=300`))?.items||[];state.waf=(await j(`${API}/api/policies/waf`))?.items||[];render();}
function nav(path){history.pushState({},'',path);render();}
window.onpopstate=()=>render();

function shell(content){const path=location.pathname;return `<div class='shell'><aside class='sidebar'><h1>IronShield</h1>${routes.map(([p,l])=>`<a class='${p===path?'active':''}' href='${p}' data-nav='1'>${l}</a>`).join('')}</aside><main class='content'><div class='top'><h2>Edge Security Control Plane</h2><span class='badge'>${new Date().toLocaleTimeString()}</span></div>${content}</main></div>`}
function kpi(){const blocked=state.events.filter(e=>e.decision==='block').length;const allow=state.events.length-blocked;return `<div class='kpis'><div class='kpi'>Total<br><b>${state.events.length}</b></div><div class='kpi'>Allowed<br><b>${allow}</b></div><div class='kpi'>Blocked<br><b class='orange'>${blocked}</b></div><div class='kpi'>p95 latency<br><b>${p95(state.events.map(e=>e.latency_ms||0)).toFixed(1)}ms</b></div></div>`}
function p95(arr){if(!arr.length)return 0;const a=[...arr].sort((x,y)=>x-y);return a[Math.floor(a.length*.95)]||0}
function table(rows){if(!rows.length)return '<div class="panel">No data</div>';const keys=Object.keys(rows[0]);return `<div class='panel'><table><thead><tr>${keys.map(k=>`<th>${k}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,80).map(r=>`<tr>${keys.map(k=>`<td>${r[k]??''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function overview(){const top=Object.entries(state.events.reduce((a,e)=>{a[e.reason]=(a[e.reason]||0)+1;return a;},{})).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>({threat:k,count:v}));return shell(`<h3>Overview</h3>${kpi()}${table(top)}`)}
function attackMap(){const dc={x:650,y:180};const points={US:[180,170],DE:[410,120],BR:[270,290],IN:[530,180],Unknown:[80,60]};const lines=state.events.slice(0,60).map(e=>{const p=points[e.country]||points.Unknown;const c=e.decision==='block'?'#f97316':'#38bdf8';return `<line x1='${p[0]}' y1='${p[1]}' x2='${dc.x}' y2='${dc.y}' stroke='${c}' stroke-opacity='.6'/>`;}).join('');const ticker=state.events.slice(0,30).map(e=>`<div>${e.ip} ${e.path} ${e.decision}/${e.reason}</div>`).join('');return shell(`<h3>Live Attack Map</h3><svg class='map' viewBox='0 0 800 400'><rect width='800' height='400' fill='#0b1220'/>${lines}<circle cx='${dc.x}' cy='${dc.y}' r='7' fill='#f97316'/></svg><div class='panel ticker'>${ticker}</div>`)}
function events(){return shell(`<h3>Events Explorer</h3>${table(state.events.map(e=>({ts:new Date(e.ts*1000).toLocaleTimeString(),decision:e.decision,reason:e.reason,ip:e.ip,country:e.country,path:e.path,status:e.status_code})))}`)}
function waf(){return shell(`<h3>WAF Rulesets</h3><div class='panel'><input id='pattern' value='select'/><button id='add-rule'>Add rule</button></div>${table(state.waf)}`)}
function rate(){return shell(`<h3>Rate Limiting</h3><div class='panel'><button id='ua-on'>Enable Under Attack</button><button id='ua-off'>Disable</button></div><p>Token bucket policy simulator with per-IP limits.</p>`)}
function geo(){return shell(`<h3>Geo Policy</h3><div class='panel'><input id='geo' placeholder='country code e.g. US'/><button id='deny-geo'>Deny country</button></div><p>Use x-forwarded-for to simulate geo lookups.</p>`)}
function bot(){return shell(`<h3>Bot Management</h3><div class='panel'>Challenge mode blocks known bad user agents with reason=bot_challenge.</div>`)}
function deployments(){return shell(`<h3>Deployments</h3><div class='panel'><button id='compile'>Compile Snapshot</button><button id='activate'>Activate Last</button></div><pre>${state.snapshot?JSON.stringify(state.snapshot,null,2):'No compiled snapshot yet.'}</pre>`)}
function analytics(){const lat=state.events.map(e=>e.latency_ms||0);return shell(`<h3>Analytics</h3>${kpi()}<div class='panel'>Latency avg ${(lat.reduce((a,b)=>a+b,0)/(lat.length||1)).toFixed(2)} ms<br/>Bandwidth saved estimate ${(state.events.filter(e=>e.decision==='block').length*2.1).toFixed(1)} MB</div>`)}
function runbooks(){return shell(`<h3>Runbooks</h3><div class='panel'><pre>Incident response checklist\n1) POST /api/config/under_attack {"enabled": true}\n2) POST /api/deployments/compile\n3) POST /api/deployments/activate/{id}\n4) Inspect /api/events and /ws/events</pre></div>`)}

function render(){const app=document.getElementById('app');const m={'/':overview,'/attack-map':attackMap,'/events':events,'/waf':waf,'/rate':rate,'/geo':geo,'/bot':bot,'/deployments':deployments,'/analytics':analytics,'/runbooks':runbooks};const fn=m[location.pathname]||overview;app.innerHTML=fn();bind();}
function bind(){document.querySelectorAll('[data-nav]').forEach(a=>a.onclick=(e)=>{e.preventDefault();nav(a.getAttribute('href'));});const add=document.getElementById('add-rule');if(add)add.onclick=async()=>{const pattern=document.getElementById('pattern').value;await j(`${API}/api/policies/waf`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({field:'query',operator:'contains',pattern,reason:'dashboard-custom',priority:5})});refresh();};const on=document.getElementById('ua-on');if(on)on.onclick=()=>j(`${API}/api/config/under_attack`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:true})});const off=document.getElementById('ua-off');if(off)off.onclick=()=>j(`${API}/api/config/under_attack`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:false})});const d=document.getElementById('deny-geo');if(d)d.onclick=()=>j(`${API}/api/config/geo_denylist`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({denylist:[document.getElementById('geo').value]})});const c=document.getElementById('compile');if(c)c.onclick=async()=>{state.snapshot=await j(`${API}/api/deployments/compile`,{method:'POST'});render();};const a=document.getElementById('activate');if(a)a.onclick=async()=>{if(state.snapshot){await j(`${API}/api/deployments/activate/${state.snapshot.id}`,{method:'POST'});alert('activated')}}}

const ws=new WebSocket('ws://localhost:8000/ws/events');ws.onmessage=(ev)=>{try{const item=JSON.parse(ev.data);state.events.unshift(item);state.events=state.events.slice(0,300);if(['/','/attack-map','/events','/analytics'].includes(location.pathname))render();}catch{}}
refresh();setInterval(refresh,5000);
